/**
 * debate-orchestrator — headless debate bus (pi-messenger-inspired semantics).
 *
 * Commands mirror harness_debate_* tools; shared state lives in debate-bus-core.
 */

import { join } from "node:path";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import {
	acceptDebateRound,
	finalizeDebateConsensus,
	openDebateBus,
	parseRoundEnvelope,
} from "../lib/debate-bus-core.js";
import {
	getDebateState,
	restoreDebateStateFromEntry,
} from "../lib/debate-bus-state.js";
import { isHarnessProjectEnabled } from "../lib/harness-project-config.js";
import { getRunIdFromSession } from "../lib/harness-run-context.js";
import { completeDebateOpen } from "../lib/harness-slash-completions.js";
import { normalizePlanDebateId } from "../lib/plan-debate-id.js";
import { initPlanMessenger } from "../lib/plan-messenger.js";

function getRunId(ctx: {
	sessionManager: { getEntries(): unknown[]; getSessionId(): string };
}): string {
	return (
		getRunIdFromSession(
			ctx.sessionManager.getEntries(),
			ctx.sessionManager.getSessionId(),
		) ?? ctx.sessionManager.getSessionId()
	);
}

export default function debateOrchestrator(pi: ExtensionAPI) {
	if (!isHarnessProjectEnabled()) return;
	const hooks = {
		appendEntry: (customType: string, data: unknown) =>
			pi.appendEntry(customType, data),
	};

	pi.on("session_start", async (_event, ctx) => {
		const entries = ctx.sessionManager.getEntries();
		for (let i = entries.length - 1; i >= 0; i--) {
			const entry = entries[i];
			if (
				entry.type === "custom" &&
				entry.customType === "harness-debate-state"
			) {
				restoreDebateStateFromEntry(entry.data);
				break;
			}
		}
	});

	pi.registerCommand("harness-debate-open", {
		description: "Open a headless debate session",
		getArgumentCompletions: (prefix) =>
			completeDebateOpen(prefix, process.cwd()),
		handler: async (args, ctx) => {
			const runId = getRunId(ctx);
			const trimmed = args.trim();
			const { debateId, warning } = normalizePlanDebateId(trimmed, runId);
			await openDebateBus(runId, debateId, hooks);
			if (debateId.startsWith("plan-")) {
				await initPlanMessenger(
					join(process.cwd(), ".pi", "harness", "runs", runId),
					{ runId, debateId },
				);
			}
			pi.sendMessage({
				customType: "harness-debate-opened",
				content: warning
					? `Debate opened: ${debateId} (${warning})`
					: `Debate opened: ${debateId}`,
				display: false,
			});
		},
	});

	pi.registerCommand("harness-debate-round", {
		description: "Submit a debate round envelope JSON",
		handler: async (args, ctx) => {
			if (!getDebateState()) {
				const runId = getRunId(ctx);
				const { debateId } = normalizePlanDebateId("", runId);
				await openDebateBus(runId, debateId, hooks);
			}
			const envelope = parseRoundEnvelope(args.trim());
			if (!envelope) {
				pi.sendMessage({
					customType: "harness-debate-round-error",
					content:
						"Invalid debate envelope JSON. Expect protocol=pi-debate-bus/v1, kind=round.",
					display: true,
				});
				return;
			}
			const result = await acceptDebateRound(envelope, hooks);
			if (!result.ok) {
				pi.sendMessage({
					customType: "harness-debate-round-rejected",
					content: `Round rejected: ${result.reason ?? "unknown reason"}`,
					display: true,
				});
			}
		},
	});

	pi.registerCommand("harness-debate-consensus", {
		description: "Finalize debate and emit consensus packet",
		handler: async (args) => {
			if (!getDebateState()) {
				pi.sendMessage({
					customType: "harness-debate-consensus-error",
					content: "No active debate to finalize.",
					display: true,
				});
				return;
			}
			const decision = await finalizeDebateConsensus(
				args.trim() || "Consensus generated by debate-orchestrator.",
				hooks,
			);
			pi.sendMessage({
				customType: "harness-debate-consensus",
				content: `Consensus decision: ${decision ?? "unknown"}`,
				display: true,
			});
		},
	});
}
