import json
from pathlib import Path
from networkx.readwrite import json_graph
from collections import defaultdict


def book_short(sf):
    if not sf:
        return 'unknown'
    name = sf.split('/')[-1]
    if 'Kahneman' in name: return 'Kahneman (TFS)'
    if 'Ariely' in name or 'Predictably' in name: return 'Ariely'
    if 'Cialdini' in name or 'Influence' in name: return 'Cialdini'
    if 'Greene' in name and 'Laws of Human Nature' in name: return 'Greene'
    if 'Dweck' in name or 'Mindset' in name: return 'Dweck'
    if 'Frankl' in name or 'Search for Meaning' in name: return 'Frankl'
    if 'Haidt' in name or 'Happiness' in name: return 'Haidt'
    if 'Murphy' in name or 'Subconscious' in name: return 'Murphy'
    if 'Crucial Conversations' in name: return 'Patterson (CC)'
    if 'Fundamentals of Software Architecture' in name: return 'Richards (FSA)'
    if 'Designing Data-Intensive' in name: return 'Kleppmann (DDIA)'
    if 'Computer Systems' in name and 'Programmer' in name: return 'Bryant (CSAPP)'
    if 'Team Topologies' in name: return 'Skelton (TT)'
    if 'Thinking in Systems' in name: return 'Meadows'
    if 'Pragmatic Programmer' in name: return 'Hunt/Thomas (PP)'
    if 'Code Complete' in name: return 'McConnell (CC2)'
    if 'Philosophy of Software Design' in name: return 'Ousterhout'
    if 'Effective Engineer' in name: return 'Lau (EE)'
    if 'Introduction to Algorithms' in name: return 'CLRS'
    if 'Pmbok' in name or 'Project Management Body of Knowledge' in name: return 'PMBOK'
    if 'Project Management' in name and 'Systems Approach' in name: return 'Kerzner'
    if 'Berkun' in name or 'Making Things Happen' in name: return 'Berkun'
    if 'Peopleware' in name: return 'DeMarco/Lister'
    if 'High Output Management' in name or 'Andrew S. Grove' in name: return 'Grove'
    if "Manager's Path" in name or 'Fournier' in name: return 'Fournier'
    if 'Elegant Puzzle' in name or 'Larson, William' in name: return 'Larson'
    if 'Scaling Teams' in name: return 'Grosse/Loftesness'
    if 'Lean Lexicon' in name: return 'Lean Lexicon'
    return name[:25]


def main():
    data = json.loads(Path('graphify-books-out/graph.json').read_text())
    G = json_graph.node_link_graph(data, edges='links')
    label_of = {nid: G.nodes[nid].get('label', nid) for nid in G.nodes()}
    book_of = {nid: book_short(G.nodes[nid].get('source_file', '')) for nid in G.nodes()}

    bridges = []
    for u, v, eattrs in G.edges(data=True):
        sf = eattrs.get('source_file', '')
        if 'cross-book-linking' in sf:
            bridges.append({
                'source': u,
                'target': v,
                'source_label': label_of[u],
                'target_label': label_of[v],
                'source_book': book_of[u],
                'target_book': book_of[v],
                'confidence': eattrs.get('confidence_score', 0.0),
                'rationale': eattrs.get('rationale', ''),
                'theme': sf.split('/')[-1] if '/' in sf else sf,
            })

    bridges.sort(key=lambda b: -b['confidence'])

    print(f'Total cross-book bridges: {len(bridges)}')
    print()

    book_pair_count = defaultdict(int)
    for b in bridges:
        pair = tuple(sorted([b['source_book'], b['target_book']]))
        book_pair_count[pair] += 1

    top_pairs = sorted(book_pair_count.items(), key=lambda x: -x[1])[:25]
    print('Top book-pair connections:')
    for (b1, b2), n in top_pairs:
        print(f'  {n:>3}  {b1} <-> {b2}')

    md = ['# Cross-Book Bridges', '']
    md.append(f'Generated by the cross-book linking pass. **{len(bridges)} new edges** connect concepts that the same author called by different names, or analogous mechanisms across domains.\n')
    md.append('## Top book-pair densities')
    md.append('| Books | Bridges |')
    md.append('|---|---|')
    for (b1, b2), n in top_pairs:
        md.append(f'| {b1} ↔ {b2} | {n} |')
    md.append('')

    high_conf = [b for b in bridges if b['confidence'] >= 0.90]
    md.append(f'## High-confidence equivalences (score ≥ 0.90, total {len(high_conf)})')
    md.append('Concepts in different books that mean essentially the same thing:\n')
    seen_pairs = set()
    for b in high_conf[:80]:
        pair = frozenset([b['source'], b['target']])
        if pair in seen_pairs:
            continue
        seen_pairs.add(pair)
        md.append(f'- **{b["source_label"]}** [{b["source_book"]}] ↔ **{b["target_label"]}** [{b["target_book"]}] _(score {b["confidence"]:.2f})_')
        if b['rationale']:
            md.append(f'  - _{b["rationale"]}_')
    md.append('')

    cross_theme = [b for b in bridges if b['confidence'] >= 0.65 and b['confidence'] < 0.85]
    is_cross_theme_pair = lambda b1, b2: True
    md.append(f'## Surprising cross-domain analogies (score 0.65-0.85)')
    md.append('Same mechanism, different domains:\n')
    seen_pairs = set()
    count = 0
    for b in cross_theme:
        pair = frozenset([b['source'], b['target']])
        if pair in seen_pairs:
            continue
        seen_pairs.add(pair)
        md.append(f'- **{b["source_label"]}** [{b["source_book"]}] ↔ **{b["target_label"]}** [{b["target_book"]}] _(score {b["confidence"]:.2f})_')
        if b['rationale']:
            md.append(f'  - _{b["rationale"]}_')
        count += 1
        if count >= 100:
            break
    md.append('')

    Path('graphify-books-out/CROSS_BOOK_BRIDGES.md').write_text('\n'.join(md))
    print()
    print('Wrote graphify-books-out/CROSS_BOOK_BRIDGES.md')


if __name__ == '__main__':
    main()
